# -*- coding: utf-8 -*-
"""Python basics HW6 Task 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TqK-9W_Ssm0jTe33a6IZDd8gy1UDe9ax

2. Реализовать класс Road (дорога), в котором определить атрибуты: length (длина), width (ширина). Значения данных атрибутов должны передаваться при создании экземпляра класса. Атрибуты сделать защищенными. Определить метод расчета массы асфальта, необходимого для покрытия всего дорожного полотна. Использовать формулу: длина * ширина * масса асфальта для покрытия одного кв метра дороги асфальтом, толщиной в 1 см * чи сло см толщины полотна. Проверить работу метода.
Например: 20м * 5000м * 25кг * 5см = 12500 т
"""

class Road:
    _weight_per_cm = 25 

    def __init__(self, length, width):
        self._length = length
        self._width = width

    def asphalt_weight(self):
        self._cm = int(input('Какой толщины (в см) положим асфальт? \n'))
        if self._length * self._width * self._weight_per_cm * self._cm > 1000:
            return f'Чтобы покрыть дорогу {self._length} м x {self._width} м асфальтом в {self._cm} см, нужно {(self._length * self._width * self._weight_per_cm * self._cm) / 1000} т асфальта'
        else:
            return f'Чтобы покрыть дорогу {self._length} м x {self._width} м асфальтом в {self._cm} см, нужно {self._length * self._width * self._weight_per_cm * self._cm} кг асфальта'

fifth_street = Road(2000, 50)

fifth_street.asphalt_weight()