# -*- coding: utf-8 -*-
"""Python basics HW8 Task 4-6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W4q-qT9WGhSe3eXasx_f0uevvhKvZZs0

4. Начните работу над проектом «Склад оргтехники». Создайте класс, описывающий склад. А также класс «Оргтехника», который будет базовым для классов-наследников. Эти классы — конкретные типы оргтехники (принтер, сканер, ксерокс). В базовом классе определить параметры, общие для приведенных типов. В классах-наследниках реализовать параметры, уникальные для каждого типа оргтехники.

5. Продолжить работу над первым заданием. Разработать методы, отвечающие за приём оргтехники на склад и передачу в определенное подразделение компании. Для хранения данных о наименовании и количестве единиц оргтехники, а также других данных, можно использовать любую подходящую структуру, например словарь.

6. Продолжить работу над вторым заданием. Реализуйте механизм валидации вводимых пользователем данных. Например, для указания количества принтеров, отправленных на склад, нельзя использовать строковый тип данных.
Подсказка: постарайтесь по возможности реализовать в проекте «Склад оргтехники» максимум возможностей, изученных на уроках по ООП.
"""

class Storage:
    def __init__(self):
        self.__inventory = set()
        print('Склад открыт')

    def __str__(self):
        return f'На складе {len(self.__inventory)} единиц техники'  

    def is_in_storage(self, unit):
        return unit in self.__inventory

    def put_to_storage(self, unit):
        if not isinstance(unit, Item):
            print('Склад принимает только оргтехнику')
        elif self.is_in_storage(unit):
            print('Эта единица техники уже на складе')
        else:
            self.__inventory.add(unit)
            return 'Единица добавлена на склад'

    def get_inventory(self):
        return self.__inventory

    def put_on_sale(self, unit):
        if not isinstance(unit, Item):
            print('На складе только оргтехника')
        elif not self.is_in_storage(unit):
            print('Такой единицы техники нет складе')
        else:
            self.__inventory.remove(unit)
            return 'Единица техники отправлена на продажу'

class Item:
    def __init__(self, brand, price):
        self.brand = brand
        self.price = price
        self.on = False     

    def operate(self):
        print('Устройство работает нормально')


class Xerox(Item):
    xerox_count = 0
    __xerox_totalprice = 0

    def __init__(self, brand, price):
        super().__init__(brand, price)
        self.copies = int(input('Укажите число копий за цикл '))
        Xerox.xerox_count += 1
        Xerox.__xerox_totalprice += price

    def operate(self):
        n = int(input('Сколько циклов копирования провести? '))
        return f'Сделано {n * self.copies} копий'

    @staticmethod
    def get_total():
        return f'Суммарная стоимость ксероксов: {Xerox.__xerox_totalprice}'


class Printer(Item):
    printer_count = 0
    __printer_totalprice = 0

    def __init__(self, brand, price):
        super().__init__(brand, price)
        self.speed = int(input('Укажите скорость печати '))
        self.color = bool(input('Печать цветная? 1 - да, 0 - нет '))
        Printer.printer_count += 1
        Printer.__printer_totalprice += price

    @staticmethod
    def get_total():
        return f'Суммарная стоимость принтеров: {Printer.__printer_totalprice}'


class Scanner(Item):
    scanner_count = 0
    __scanner_totalprice = 0

    def __init__(self, brand, price):
        super().__init__(brand, price)
        self.dpi = str(input('Укажите разрешение сканера '))        
        Scanner.scanner_count += 1
        Scanner.__scanner_totalprice += price

    @staticmethod
    def get_total():
        return f'Суммарная стоимость сканеров: {Scanner.__scanner_totalprice}'

warehouse = Storage()

warehouse.get_inventory()

warehouse.is_in_storage(item1)

warehouse.put_on_sale(item1)

print(warehouse)

item1 = Xerox('canon', 50000)

warehouse.put_to_storage(item1)

item2 = Xerox('hp', 200)

warehouse2.put_to_storage(item1)

Xerox.get_total()