# -*- coding: utf-8 -*-
"""Python basics HW3 Task 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cqKSIpFxyLVvbbb5f10u_ULT3XlEu2li

Программа запрашивает у пользователя строку чисел, разделенных пробелом. При нажатии Enter должна выводиться сумма чисел. Пользователь может продолжить ввод чисел, разделенных пробелом и снова нажать Enter. Сумма вновь введенных чисел будет добавляться к уже подсчитанной сумме. Но если вместо числа вводится специальный символ, выполнение программы завершается. Если специальный символ введен после нескольких чисел, то вначале нужно добавить сумму этих чисел к полученной ранее сумме и после этого завершить программу.
"""

def summarize():
    s = 0
    while s == s:
        userlist = input('Введите числа, разделяя их пробелами. Нажмите N для завершения работы \n').split(' ')
        for i in userlist:
            if i == 'N' or i == 'n':
                print(f'Итоговая сумма равна {s}')
                return s
            s += float(i)
        print(s)
    return s

summarize()