# -*- coding: utf-8 -*-
"""Python basics HW3 Task 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oneAVsxk1JVGjPOth1FFII0u8Ff7UVwU

Программа принимает действительное положительное число x и целое отрицательное число y. Необходимо выполнить возведение числа x в степень y. Задание необходимо реализовать в виде функции my_func(x, y). При решении задания необходимо обойтись без встроенной функции возведения числа в степень. Подсказка: попробуйте решить задачу двумя способами. Первый — возведение в степень с помощью оператора *. Второй — более сложная реализация без оператора *, предусматривающая использование цикла.
"""

def my_func2(x, y):

    while x < 0:
        if x < 0:
            x = float(input('Неправильный х, введите положительное число \n'))

    while y > 0 or type(y) == float:
        if y > 0 or type(y) == float:
            try:
                y = int(input('Неправильный y, введите целое отрицательное число \n'))    
            except ValueError:
                print('Ошибка: y должен быть целым числом')
                return

    print(f'х в степени y равно {x ** y}')

"""Вариант без оператора *"""

my_func2(x=0, y=0)

def my_func3(x, y):

    while x < 0:
        if x < 0:
            x = float(input('Неправильный х, введите положительное число \n'))

    while y > 0 or type(y) == float:
        if y > 0 or type(y) == float:
            try:
                y = int(input('Неправильный y, введите целое отрицательное число \n'))    
            except ValueError:
                print('Ошибка: y должен быть целым числом')
                return

    res = 1
    for i in range(abs(y)):     # эта строка задает повтор следующей строки |y| раз
        res /= x                # эта строка res делит на x

    print(f'х в степени y равно {res}')

my_func3(x=2, y=-3)